src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Usager::class, inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private $usager;

    #[ORM\Column(type: 'date')]
    private $date_commande;

    #[ORM\Column(type: 'string', length: 255)]
    private $statut;

    #[ORM\OneToMany(mappedBy: 'commande', targetEntity: LigneCommande::class)]
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsager(): ?Usager
    {
        return $this->usager;
    }

    public function setUsager(?Usager $usager): self
    {
        $this->usager = $usager;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }
}

src/Entity/Usager.php
<?php

namespace App\Entity;

use App\Repository\UsagerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsagerRepository::class)]
class Usager implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\OneToMany(mappedBy: 'usager', targetEntity: Commande::class)]
    private $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUsager($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUsager() === $this) {
                $commande->setUsager(null);
            }
        }

        return $this;
    }
}

src/Form/UsagerType.php
<?php

namespace App\Form;

use App\Entity\Usager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsagerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class)
            ->add('password', PasswordType::class)
            ->add('nom')
            ->add('prenom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Usager::class,
        ]);
    }
}

src/Controller/UsagerController.php
<?php

namespace App\Controller;

use App\Entity\Usager;
use App\Form\UsagerType;
use App\Repository\UsagerRepository;
use Doctrine\DBAL\Types\TextType;
use Doctrine\ORM\EntityManagerInterface;
use PhpParser\Builder\Use_;
use App\Service\MailService;
use PHPUnit\TextUI\XmlConfiguration\CodeCoverage\Report\Text;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;

/**
 * @Route("/{_locale}/usager", requirements={"_locale"="%app.supported_locales%"}, defaults={"_locale"="fr"})
 */
class UsagerController extends AbstractController
{
    public function index(UsagerRepository $usagerRepository, SessionInterface $session): Response
    {
        $usager = $this->getUser();
        $usagerCommande = count($usager->getCommandes());

        return $this->render('usager/index.html.twig', [
            'usager' => $usagerRepository->find($usager->getId()),
            'usagercommande' => $usagerCommande
        ]);
    }


    public function new(Request $request, EntityManagerInterface $entityManager, SessionInterface $session, UserPasswordHasherInterface $passwordHasher, MailService $mailer): Response
    {

        $usager = new Usager();

        $form = $this->createForm(UsagerType::class, $usager);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->addFlash('sucesse', 'Vous avez été bien inscrit');
            // Encoder le mot de passe qui est en clair pour l’instant
            $hashedPassword = $passwordHasher->hashPassword($usager, $usager->getPassword());
            $usager->setPassword($hashedPassword);
            // Définir le rôle de l’usager qui va être créé 
            $usager->setRoles(["ROLE_CLIENT"]);

            $entityManager->persist($usager);

            $entityManager->flush();
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('usager/new.html.twig', [
            'usager' => $usager,
            'form' => $form
        ]);
    }

    public function commandes(SessionInterface $session)
    {
        $usager = $this->getUser();
        $devise = $session->get('devise');
        $commandes = $usager->getCommandes();

        return $this->renderForm('usager/commande.html.twig', [
            'commandes' => $commandes,
            'devise' => $devise
        ]);
    }
}

templates/usager/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}


{{ form_start(form) }}
	{# <div class="row">
		<div class="col">{{ form_row(form.email) }}</div>
		<div class="col">{{ form_row(form.password) }}</div>
	</div>
	<div class="row">
		<div class="col">{{ form_row(form.nom) }}</div>
		<div class="col">{{ form_row(form.prenom) }}</div>
	</div>
	{{ form_rest(form) }}
	<div class="form-group">
		<button class="btn btn-lg btn-primary">Inscription</button>

	</div> #}
	<div class="card col-md-8 offset-2">
		<div class="card-header">
			<h3><i class="fas fa-user-plus"></i> Nouveau Membre : Inscription</h3>
		</div>
		<div class="card-body">
	
                
				<div class="form-group">
                    {{ form_row(form.email) }}
				
                </div>
				<div class="form-group">
                    {{ form_row(form.password) }}
           		</div>
                   <div class="form-group">
                    {{ form_row(form.nom) }}
           		</div>
                   <div class="form-group">
                    {{ form_row(form.prenom) }}
           		</div>
				   {{ form_rest(form) }}
                <div class="col-md-12 btn-group" style="padding:0px">

					<button class="btn btn-lg btn-primary">Inscription</button>

                </div> 
			</form>
		</div>
	</div>

{{ form_end(form) }}

templates/usager/commande.html.twig
{# template/usager/commande.html.twig#}
{% extends 'base.html.twig' %}

{% block title %}
	Mes Commandes
{% endblock %}

{% block body %}
	<div class="col-8 offset-2">
		<div class="card">
			<div class="card-header">
				<h3>
					<i class="fas fa-user-check"></i>
					{% trans %}navbar.mescommandes{% endtrans %}</h3>
			</div>
			<div class="card-body">
				<table class="table table-striped table-sm table-hover">
					<thead>
						<tr>
							<th>N°</th>
							<th>Date</th>
							<th>Produits</th>
							<th>Montant</th>
							<th>Statut</th>
						</tr>
					</thead>
					<tbody>
						{% if commandes is empty %}
							<tr>
								<td colspan="5">Pas de Commandes Trouvées</td>
							</tr>

						{% else %}

							{% for commande in commandes %}
								<tr class="text-danger" style='font-weight: bold;'>
									<td>{{commande.id}}</td>
									<td>{{commande.dateCommande|date('d-m-Y') }}</td>
                                    {% set ligneCommandes = commande.ligneCommandes %}
                                    {% set totalPrix = 0 %}
                                    {% set totalQuantite = 0 %}
									{% for ligneCommande in ligneCommandes %}
                                        {% set totalQuantite = totalQuantite + ligneCommande.quantite %}
                                        {% set totalPrix = totalPrix + ligneCommande.prix %}
                                    {% endfor %}
									<td>{{ totalQuantite }}</td>
                                    <td>{{ totalPrix|currency_convert|format_currency(devise)}} </td>
                                    <td>
										<i class="fas fa-hourglass-half" data-toggle="tooltip" title="validation en Attente" data-placement="right"></i>
									</td>
								</tr>
							{% endfor %}

						{% endif %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

{% endblock %}

templates/usager/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usager index{% endblock %}

{% block body %}
      <div class="col-8 offset-2">
        <div class="card">
            <div class="card-header">
                <h3><i class="fas fa-user-check"></i> Mon Compte</h3>
            </div>
            <div class="card-body">
                <table class="table table-striped table-sm table-hover">
                    <tr><th>N° Client</th><td>{{app.user.id}}</td></tr>
                    <tr><th>Nom</th><td>{{app.user.nom}}</td></tr>
                    <tr><th>Prénom</th><td>{{app.user.prenom}}</td></tr>
                    <tr><th>Email</th><td>{{app.user.email}}</td></tr>
                    <tr><th>Activité</th>
                        <td>
                            <a class="btn btn-primary" href="{{ path('usager_commandes') }} ">
                                <span class="badge badge-light">{{usagercommande}}</span> Commande(s)                            
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/usager/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Usager{% endblock %}

{% block body %}

    {{ include('usager/_form.html.twig') }}
    
{% endblock %}